created a block of notes
roll-over/unknown-interview pull request #122
Opened 2023-09-07 09:37 UTC by OvchariK3208

2023-09-07 09:56 UTC, OvchariK3208 reviewed
случайно был добавлен файл package-lock.json и +layout.svelte, постарался удалить из pull request

2023-09-07 13:11 UTC, HugeLetters requested changes

2023-09-07 13:11 UTC, HugeLetters commented on frontend/package-lock.json
Не тот пэкэдж менеджер

2023-09-07 13:11 UTC, HugeLetters commented on frontend/src/routes/profile/matches/[id]/+page.svelte
Есть же макет уже

2023-09-10 13:59 UTC, HugeLetters requested changes

2023-09-10 13:59 UTC, HugeLetters commented on frontend/src/routes/profile/matches/[id]/+page.svelte
> +					<li class="max-w-lg rounded-lg p-3 bg-slate-500 max-xl">
`max-xl` - опечатка

2023-09-10 13:59 UTC, HugeLetters commented on frontend/src/routes/profile/matches/[id]/+page.svelte
Все гуд, только если заметок будет меньше, то высота блока с записками будет не треть, а меньше. Но я хз как по макету правильно - чтоб она всегда была треть, или просто не превышала треть.
И также файл не отформатирован - видно по порядку классов. У нас же не просто так плагин для Преттиера в рекомендуемых

2023-09-11 15:19 UTC, HugeLetters approved these changes

2023-09-11 15:26 UTC, merged