add new forms for job and emploees
roll-over/unknown-interview pull request #36
Opened 2023-08-27 14:58 UTC by orby-tech

2023-08-27 15:41 UTC, HugeLetters commented on frontend/src/routes/+page.svelte
> +		class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 dark:text-white md:text-5xl lg:text-6xlmb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5
Так, ну классы можно и не по 3 раза повторять)))

2023-08-28 15:51 UTC, HugeLetters requested changes

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +			on:click={() => newEmployState.update((a) => ({ ...a, position }))}
`on:click={() => ($newEmployState.position = position)}`

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +		on:click={() => {
`on:click={() => ($newEmployState.salaryFork.applied = true)}`

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +{:else if $newEmployState.salaryFork && (!$newEmployState.salaryFork?.min || !$newEmployState.salaryFork?.max || !$newEmployState.salaryFork?.applied)}
Просто можно сделать реактивное значение
```ts
$: salaryForkFilledIn = !!$newEmployState.salaryFork.min && !!$newEmployState.salaryFork.max
```
и потом им пользоваться тут и в кнопке ниже

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +{#if !$newEmployState.position}
Может, лучше одну большую форму сделать? Тут не так много шагов, чтоб делать мульти-степ + если делать мульти-степ, то тогда уже куда проще будет шаги конкретные прописать и контролить какой шаг отображать. А то в таком виде форму ни отредачить, ни вернуться назад.

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
Также, думаю, тут многие инпуты можно просто в компоненты вывести

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +	<h1>Your skills</h1>
Skills это массив, но выбрать можно только одно значение же, потому что сразу перекидывает на некст этап

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +			on:click={() =>
```ts
on:click={() => {
		$newEmployState.skills.push(skill);
		$newEmployState.skills = $newEmployState.skills;
                 // чтобы комплиятор свелта понял, что тут нужен ререндер
}}
```

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/job-search/+page.svelte
Ну тк пока что это просто почти то же самое, что и поиск сотрудников, то комментарии те же.

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/types/common.ts
Небольшой момент, но меньше файлов/диреторий по возможнотси - лучше. Можно просто перенести `hello/employee.ts`, а данные которые уникальные для каждой страницы - прямо в тех же `.svelte` файлах и прописать

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/types/common.ts
> +type NewJobState = {
Я бы переделал этот тип со всеми полями как требуемыми, а за null state бы просто считал пустые строки. Это и от лишних проверок в страницах избавит, да и типом этим можно будет пользоваться в других местах, а то в таком виде он только для заполнения юзерформы и нужен

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/types/common.ts
> +		applied: boolean;
Я так понял, это для того, чтоб формы не перескочила на след. шаг сразу как введены данные, а по нажатию кнопки - я считаю, это надо перенести в локальный стейт страницы, потому что это ее зона ответственности, а как резюме сотрудника отношения не имеет

2023-08-28 15:51 UTC, HugeLetters commented on frontend/src/routes/hello/types/common.ts
> +		applied: boolean;
Я так понял, это для того, чтоб формы не перескочила на след. шаг сразу как введены данные, а по нажатию кнопки - я считаю, это надо перенести в локальный стейт страницы, потому что это ее зона ответственности, а как резюме сотрудника отношения не имеет

2023-08-29 02:22 UTC, orby-tech commented on frontend/src/routes/+page.svelte
> +		class="lg:text-6xlmb-4 dark:text-whitemb-4 mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 dark:text-white dark:text-white md:text-5xl"
+

2023-08-29 02:22 UTC, orby-tech commented on frontend/src/routes/+page.svelte
> +		class="mb-2 mr-2 rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark
+

2023-08-29 02:45 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
Чтобы при перезагрузке страницы пользователь не потерял стейт

2023-08-29 02:45 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
Чтобы при перезагрузке страницы пользователь не потерял стейт

Эта проблема немного сгладилсь тем что я переделал на общую форму

2023-08-29 02:46 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
Да, вынесем, но мне кажется потом

Можно будет кучку мини задач сделать по всякому фуенкционалу, у нас как раз много ребят на которых это можно параллелить

2023-08-29 02:46 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
> +{#if !$newEmployState.position}
+

2023-08-29 02:49 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
> +			on:click={() => newEmployState.update((a) => ({ ...a, position }))}
Гуууд

2023-08-29 02:51 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
> +{:else if $newEmployState.salaryFork && (!$newEmployState.salaryFork?.min || !$newEmployState.salaryFork?.max || !$newEmployState.salaryFork?.applied)}
Очень кайфовая история, спасибо

Применить здесь не удасться тк, я переделал на общую форму

2023-08-29 02:51 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
> +		on:click={() => {
+

2023-08-29 02:53 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
> +	<h1>Your skills</h1>
Тут это опять же связано с тем что так проще параллелить задачи, потом просто будет таска на сделать нормальный скил сет

Цель этого реквеста сделать страницы по которым уже будут задачи на конкретные блоки

2023-08-29 02:54 UTC, orby-tech commented on frontend/src/routes/hello/employees-search/+page.svelte
> +			on:click={() =>
Думаю, чтобы не ломать консистентность, лучше пока массив из одного скила оставить (я переделал, но чуть по другому)

2023-08-29 02:56 UTC, orby-tech commented on frontend/src/routes/hello/types/common.ts
Вынес

Типы и дефолты я пока там оставил, чтобы потом когда будем на типы из опенапи переезжать, было менее проблемно

2023-08-29 03:08 UTC, orby-tech commented on frontend/src/routes/hello/types/common.ts
> +type NewJobState = {
+

2023-08-29 03:08 UTC, orby-tech commented on frontend/src/routes/hello/types/common.ts
> +		applied: boolean;
+

2023-08-29 03:08 UTC, orby-tech commented on frontend/src/routes/hello/types/common.ts
> +		applied: boolean;
+

2023-08-29 06:52 UTC, HugeLetters commented on frontend/src/routes/hello/employees-search/+page.svelte
> +{#each skills.programmer as skill}
Только один скилл можно выбрать по такой схеме

2023-08-29 06:53 UTC, HugeLetters approved these changes

2023-08-29 07:40 UTC, merged